services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"