services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "26686:16686"
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.3'
    links:
      - zookeeper:zk
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  redis:
    image: redis
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"

  app:
    build:
      context: . 
      dockerfile: Dockerfile
    command: ["/app/main", "-c", "/app/app.toml"]
    ports:
      - "28888:8888" 
    restart: unless-stopped
    links:
      - redis
      - mysql
      - kafka
      - jaeger
    depends_on: 
      - redis 
      - mysql
      - kafka
      - jaeger
