[[ngo.client.http]]
name = "demo01"
noDefaultUserAgentHeader=true
maxConnsPerHost=41
maxIdleConnDuration=50000000000 #50s
maxConnDuration=10000000000 #10s
maxIdemponentCallAttempts=55
readBufferSize=4096
writeBufferSize=128
readTimeout= 400000000000 #4s
writeTimeout= 500000000000 # 5s
maxResponseBodySize= 2300000
maxConnWaitTimeout= 10